#!/usr/bin/env ruby

# read a dsl file
# parse the file
# generate random index (less than maximum line count of the file)
# display key
# display value

WORDS_DIR          = "/usr/local/etc/oboe"
WORDS_FILE_DEFAULT = File.join(WORDS_DIR, "words.txt")
WORDS_FILE         = ARGV[0] || WORDS_FILE_DEFAULT

abort("file missing at: #{WORDS_FILE}") if !File.exist?(WORDS_FILE)

lines = File.open(WORDS_FILE, "r").each_line.to_a

lines = lines
          .select {|line| 
             line =~ /\w+[\,]?\w+/ 
          }
          .map {|line|
             line.chomp.split(",")
          }

def disp(x)
  print "#{x}"
  input = $stdin.gets.chomp 
  abort if input =~ /[qQ]/
  input
end

def play(lines) 
  k, v = lines[rand(0..lines.size-1)]
  disp k
  disp "[#{v.strip}]"
  puts
  play(lines)
end

play lines
